(function(g){var window=this;var G7=function(a){g.Y.call(this,{H:"button",ca:["ytp-offline-slate-button","ytp-button"],K:[{H:"div",M:"ytp-offline-slate-button-icon",K:["{{icon}}"]},{H:"div",M:"ytp-offline-slate-button-text",K:["{{text}}"]}]});this.C=a;this.A=this.o=null;this.hide();this.U("click",this.D,this)},Eya=function(a,b){!a.o&&b&&b.toggleButtonRenderer?a.o=b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.o=null);
H7(a)},H7=function(a){if(a.o){if(a.o.isToggled){var b=a.o.toggledText?g.dQ(a.o.toggledText):"";
a.update({text:b,icon:Fya(a.o.toggledIcon)})}else b=a.o.defaultText?g.dQ(a.o.defaultText):"",a.update({text:b,icon:Fya(a.o.defaultIcon)});a.show()}else a.hide()},Fya=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS_NONE":return g.pE?{H:"div",ca:["ytp-icon","ytp-icon-notifications-none"]}:{H:"svg",R:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},K:[{H:"path",R:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};case "NOTIFICATIONS_ACTIVE":return g.CE();default:return null}},I7=function(a){g.Y.call(this,
{H:"div",
M:"ytp-offline-slate",K:[{H:"div",M:"ytp-offline-slate-bar",K:[{H:"span",M:"ytp-offline-slate-icon",K:[g.pE?{H:"div",ca:["ytp-icon","ytp-icon-live-icon"]}:{H:"svg",R:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},K:[{H:"path",R:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{H:"circle",R:{cx:"12",cy:"12",r:"3"}}]}]},{H:"span",M:"ytp-offline-slate-buttons"},{H:"span",M:"ytp-offline-slate-messages",K:[{H:"div",M:"ytp-offline-slate-main-text",K:["{{maintext}}"]},{H:"div",M:"ytp-offline-slate-subtitle-text",K:["{{subtitletext}}"]}]}]},{H:"div",M:"ytp-offline-slate-final-day",K:[{H:"div",M:"ytp-offline-slate-final-day-line-1",K:["Dawn of"]},{H:"div",M:"ytp-offline-slate-final-day-line-2",K:["The Final Day"]},{H:"div",M:"ytp-offline-slate-final-day-line-3",K:["-24 Hours Remain-"]}]}]});
this.A=a;this.B=this.o=null;this.C=new g.Ft(this.F,1E3,this);this.P(a,"presentingplayerstatechange",this.G);this.P(a,"livestatedata",this.D);this.hide();a=this.A.fa();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.D(a)},J7=function(a,b,c){if(b){var d=void 0!=b.subtitleText?g.dQ(b.subtitleText):"";
b=c?c:void 0!=b.mainText?g.dQ(b.mainText):"";a.update({maintext:b,subtitletext:d});g.T(a.element,"ytp-offline-slate-single-text-line",!d)}},L7=function(a){g.bX.call(this,a);
this.I=!1;this.J=0;this.G=!1;this.o=window.NaN;this.A=this.B=null;this.C=!1;this.F=null;this.L=-(new g.Jn).getTimezoneOffset();this.D=new g.qG(this);g.L(this,this.D);var b=this.g.fa();if(b.Ba){var c=g.X(this.g);g.nN()?c.experiments.g("live_fresca_v2")&&!g.aO(c)&&(this.I=this.C=!0,this.F=new I7(this.g),g.L(this,this.F),g.zW(this.g,this.F.element,4),(b=b.getPlayerResponse())&&b.playabilityStatus&&(this.A=b.playabilityStatus),this.A?(b=Gya(this.A.liveStreamability&&this.A.liveStreamability.liveStreamabilityRenderer))?
K7(this,b):K7(this,7500):K7(this,1E3)):g.jV(this.g.app.A,"html5.unsupportedlive","YTP_HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1")}this.D.P(a,"heartbeatparams",this.wM);this.D.P(a,"presentingplayerstatechange",this.xM);this.D.P(a,"videoplayerreset",this.xS);this.D.P(a,"crn_heartbeat",this.vM);this.C&&this.A&&Hya(this,this.A);b=new g.bS(1E3,0x7ffffffffffff,{priority:g.$R.nH,namespace:"heartbeat"});g.sW(a,[b])},Iya=function(a){a=a.g.fa();
return!!g.qQ(a)&&!a.gs},M7=function(a){var b=a.g.fa();
return Iya(a)?!!a.B:!!b.heartbeatToken},K7=function(a,b){if(!a.o&&a.I){var c=a.g.fa();
if(M7(a)||c.Ba)void 0==b&&(b=a.G?a.C?7500:a.B?1E3*a.B.interval:a.g.fa().heartbeatInterval||6E4:1E3),a.o=g.VE((0,g.A)(a.BT,a),b)}},Hya=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=Gya(c),e=a.g.fa();
if(g.fW(a.g).wb()&&!g.zQ(e)&&!a.g.isPeggedToLive())return d;var f=c&&c.streamTransitionEndpoint&&c.streamTransitionEndpoint.watchEndpoint.videoId;if(f)return g.R1(a.g.app,f,void 0,void 0,!0,!0),d;if("OK"==b.status.toUpperCase()){if(!e.hlsvp&&!e.ze||a.A&&c&&c.broadcastId!=a.A.liveStreamability.liveStreamabilityRenderer.broadcastId)return c={video_id:e.videoId},e.isLiveDestination&&(c.is_live_destination="1"),a.g.so(c),d;g.wW(a.g,"heartbeat")}return d},Gya=function(a){var b=0;
a&&a.pollDelayMs&&(a=(0,window.parseInt)(a.pollDelayMs,10))&&(b=a);return b},N7=function(a,b,c){if(a.o){a.o=window.NaN;
a.J++;var d=a.g.fa();(d.heartbeatSoftFail?0:a.J>=(a.B?a.B.g:d.heartbeatRetries||5))?(b=b?"heartbeat.net":"heartbeat.servererror",d=(d=a.g.fa())&&d.Ba?g.U("YTP_ERROR_STREAM_LICENSE_NOT_FOUND"):g.U("YTP_ERROR_LICENSE"),g.jV(a.g.app.A,b,d,c)):K7(a)}},O7=function(a){a.J=0;
a.o&&(g.TE(a.o),a.o=window.NaN);a.G=!1},Jya=function(a){try{return g.yg(a)}catch(b){return null}};g.p(G7,g.Y);
G7.prototype.D=function(){this.A||(this.A=new g.aH(g.X(this.C).Pg));var a={context:g.WG(this.A.g)};if(this.o.isToggled){a.params=this.o.toggledServiceEndpoint.removeUpcomingEventReminderEndpoint.params;var b="notification/remove_upcoming_event_reminder"}else a.params=this.o.defaultServiceEndpoint.addUpcomingEventReminderEndpoint.params,b="notification/add_upcoming_event_reminder";var c={timeout:5E3};c.onError=(0,g.A)(this.B,this);c.Gd=(0,g.A)(this.B,this);g.XG(this.A,b,a,c);this.o.isToggled=!this.o.isToggled;
H7(this)};
G7.prototype.B=function(){this.o&&(this.o.isToggled=!this.o.isToggled,H7(this))};g.p(I7,g.Y);
I7.prototype.D=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.o=a;b.liveStreamOfflineSlateRenderer.canShowCountdown?this.F():J7(this,b.liveStreamOfflineSlateRenderer);var c=this.element;if(b&&b.liveStreamOfflineSlateRenderer&&b.liveStreamOfflineSlateRenderer.scheduledStartTime){var d=b.liveStreamOfflineSlateRenderer.scheduledStartTime-(0,g.G)()/1E3;d=86400>=d&&86340<d}else d=!1;g.T(c,"ytp-offline-slate-show-final-day",d);if(c=a&&a.liveStreamability&&
a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail){d=0;for(var e=null,f=0;f<c.thumbnails.length;f++)c.thumbnails[f].width>d&&(d=c.thumbnails[f].width,e=c.thumbnails[f].url);e&&(this.element.style.backgroundImage="url("+e+")")}else this.element.style.backgroundImage=
"";b.liveStreamOfflineSlateRenderer.actionButtons?(this.B||(this.B=new G7(this.A),this.B.Ga(this.wa["ytp-offline-slate-buttons"]),g.L(this,this.B)),Eya(this.B,b.liveStreamOfflineSlateRenderer.actionButtons[0])):this.B&&Eya(this.B,null);this.o=a}else this.o=null;this.G()};
I7.prototype.G=function(){var a=g.fW(this.A),b=this.A.fa(),c=b.Ba&&(g.pR(a)||g.W(a,2)||g.W(a,64));a=a.wb()&&!g.zQ(b)&&!this.A.isPeggedToLive();c&&!a&&this.o&&"LIVE_STREAM_OFFLINE"==this.o.status.toUpperCase()?this.g||(this.show(),this.A.X("offlineslatestatechange")):this.g&&(this.hide(),this.A.X("offlineslatestatechange"))};
I7.prototype.F=function(){var a=this.o&&this.o.liveStreamability&&this.o.liveStreamability.liveStreamabilityRenderer&&this.o.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.o.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor((0,g.G)()/1E3),c=a.canShowCountdown&&(0,window.parseInt)(a.scheduledStartTime,10);!c||c<=b?(J7(this,a),this.C.stop()):(b=g.hX(c-b),J7(this,a,b),this.C.gc())}};
I7.prototype.W=function(){this.C.dispose();this.C=null;g.Y.prototype.W.call(this)};g.p(L7,g.bX);g.h=L7.prototype;g.h.W=function(){O7(this);g.bX.prototype.W.call(this);g.vW(this.g,"heartbeat")};
g.h.vM=function(){this.I=!0;K7(this,2E3)};
g.h.wM=function(a){this.B=a;K7(this,2E3)};
g.h.xM=function(a){g.W(a.state,2)||g.W(a.state,64)?(O7(this),this.C&&(this.I=!0,K7(this,1E3))):(g.W(a.state,1)||g.W(a.state,8))&&K7(this,2E3)};
g.h.xS=function(){3!==this.g.Ya()&&K7(this,2E3)};
g.h.BT=function(){var a=g.X(this.g),b=this.g.fa();var c=a.baseYtUrl;if(3==this.g.Ya())this.o=window.NaN;else if(g.W(g.fW(this.g),4))this.o=window.NaN;else if(M7(this)||b.Ba){if(!Iya(this)||b.Ba){var d="GET";var e=a.o;a={video_id:b.videoId,heartbeat_token:b.heartbeatToken,c:e.c,cver:e.cver,cbrand:e.cbrand,cmodel:e.cmodel,vvt:b.ng,mdx_environment:b.mdxEnvironment,access_token:b.oauthToken,forced_experiments:a.forcedExperiments,utc_offset_minutes:this.L};(e=g.kQ(b))&&(a.uloc=e);(e=this.g.vh().ingestionTime)&&
(a.ingestion_time=e);c=g.Qg(c+"heartbeat",a)}else d="GET",c=g.Qg(this.B.url,{request_id:g.UN()}),b.ng&&(c=g.Qg(c,{vvt:b.ng}),b.mdxEnvironment&&(c=g.Qg(c,{mdx_environment:b.mdxEnvironment}))),b.oauthToken&&(c=g.Qg(c,{access_token:b.oauthToken}));b.dl&&(c=g.Qg(c,{internalipoverride:b.dl}));b.innertubez&&(c=g.Qg(c,{innertubez:b.innertubez}));c=g.Qg(c,{cpn:b.clientPlaybackNonce});g.iF(c,{format:"RAW",method:d,timeout:3E4,Vb:(0,g.A)(this.MK,this),onError:(0,g.A)(this.LK,this),Gd:(0,g.A)(this.NK,this),
withCredentials:!0})}else O7(this)};
g.h.MK=function(a){if(this.o){a=a.responseText;var b=Jya(a);if(b){this.g.za("onHeartbeat",b);var c="ok"==b.status?b.stop_heartbeat?2:0:"stop"==b.status?1:"live_stream_offline"==b.status?0:-1}else c=(c=a.match(Kya))?"0"==c[1]?0:1:-1;if(-1==c)N7(this,!1,"decode");else if(2!=c||M7(this))if(this.J=0,this.o=window.NaN,1==c){this.G=!1;b=this.g;c="YTP_ERROR_LICENSE";var d=Jya(a);d?a=d.reason||g.U(c):((a=a.match(Kya))&&(a=(0,window.parseInt)(a[1],10))&&(c=g.NQ(a)),a=g.U(c));g.jV(b.app.A,"heartbeat.stop",
a,void 0)}else this.G=!0,a=0,this.C&&b&&(a=Hya(this,b),this.g.X("livestatedata",b)),a?K7(this,a):K7(this);else O7(this),this.G=!0}};
g.h.LK=function(a){N7(this,!0,"net-"+a.status)};
g.h.NK=function(){N7(this,!0,"timeout")};
g.h.uM=function(){return!!this.F&&this.F.g};
var Kya=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.nX("heartbeat",L7);})(_yt_player);
