(function(g){var window=this;var Lya=function(a,b){var c=[];g.Nl(b,function(a){try{var b=g.ED.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.DD(b)&&c.push(a):c.push(a)},a);
return c},Mya=function(a,b){var c=Lya(a,b);
(0,g.H)(c,function(a){g.ED.prototype.remove.call(this,a)},a)},P7=function(a,b){g.G0.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.T=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},Nya=function(){var a=g.mH;
Mya(a,a.g.Xd(!0))},Q7=function(a){g.PH.call(this,"ScreenServiceProxy");
this.dd=a;this.o=[];this.o.push(this.dd.$_s("screenChange",(0,g.A)(this.GU,this)));this.o.push(this.dd.$_s("onlineScreenChange",(0,g.A)(this.VQ,this)))},R7=function(a){g.CH("cloudview",a)},Oya=function(a){R7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},S7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Pya=function(a){g.FG[a]&&(a=g.FG[a],(0,g.H)(a,function(a){g.DG[a]&&delete g.DG[a]}),a.length=0)},Qya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},T7=function(){return g.x("yt.mdx.remote.connection_")},U7=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},Rya=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},V7=function(){return g.x("yt.mdx.remote.currentScreenId_")},
X7=function(){if(!W7){var a=g.x("yt.mdx.remote.screenService_");
W7=a?new Q7(a):null}return W7},Y7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},Z7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},$7=function(a){R7("setCastInstalled_ "+a);
g.oH("yt-remote-cast-installed",a)},a8=function(a){g.CH("cloudview",a)},Sya=function(a,b){S7().init(a,b)},b8=function(){return!!g.pH("yt-remote-cast-installed")},Tya=function(){R7("dispose");
var a=S7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);Oya(!1);g.HG(c8);c8.length=0},Uya=function(){var a=window.document.createElement("a");
g.Xc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.$a(a)},Vya=function(a,b){var c=g.Cd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Yc(c,g.ce("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Wya=function(a){var b=g.CG();
if(b)if(b.clear(a),a)Pya(a);else for(var c in g.FG)Pya(c)},d8=function(){var a=Qya();
a&&a(!1,"No cast extension found")},e8=function(a){return 0<=window.navigator.userAgent.indexOf(a)},f8=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},Xya=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},g8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},i8=function(a){var b=T7();
U7(null);a||Rya("");g.ua("yt.mdx.remote.connection_",a,void 0);h8&&((0,g.H)(h8,function(b){b(a)}),h8.length=0);
b&&!a?g.KG("yt-remote-connection-change",!1):!b&&a&&g.KG("yt-remote-connection-change",!0)},Yya=function(){return g.x("yt.mdx.remote.connectData_")},j8=function(){var a=V7();
if(!a)return null;var b=X7().ee();return g.OH(b,a)},Zya=function(a,b){$7(!0);
Y7(!1);Sya(a,function(a){a?(Oya(!0),g.IG("yt-remote-cast2-api-ready")):(a8("Failed to initialize cast API."),$7(!1),g.qH("yt-remote-cast-available"),g.qH("yt-remote-cast-receiver"),Tya());b(a)})},$ya=function(){return b8()?S7()?S7().getCastSession():(a8("getCastSelector: Cast is not initialized."),null):(a8("getCastSelector: Cast API is not installed!"),null)},aza=function(){var a=Uya(),b=window.document.getElementById(a),c=b&&g.SF(b,"loaded");
c||b&&!c||(b=Vya(a,function(){g.SF(b,"loaded")||(g.TF(b,"loaded","true"),g.IG(a),g.VE(g.Ga(Wya,a),0))}))},bza=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},cza=function(){if(g.Bra){var a=2,b=Qya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;f8("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",d8,c)}},k8=function(a){if(a>=g.Dra.length)d8();
else{var b=g.Dra[a],c="chrome-extension://"+b+g.Ara;0<=g.c2.indexOf(b)?Xya(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,f8(c,d8)):k8(a+1)}):f8(c,function(){k8(a+1)})}},m8=function(a,b){V7();
j8()&&j8();Rya(a.id);var c=new g.UI(l8,a,g8());c.connect(b,Yya());c.subscribe("beforeDisconnect",function(a){g.KG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){T7()&&(T7(),i8(null))});
i8(c)},n8=function(){var a=g.WH();
if(!a)return null;var b=X7().ee();return g.OH(b,a)},o8=function(a){g.CH("remote",a)},p8=function(){var a=T7();
return!!a&&3!=a.getProxyState()},q8=function(){Z7()?S7().stopSession():a8("stopSession called before API ready.");
var a=T7();a&&(a.disconnect(1),i8(null))},dza=function(){var a=X7().dd.$_gos();
var b=j8();b&&T7()&&(g.NH(a,b)||a.push(b));return bza(a)},s8=function(a,b){g.tG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.SB;this.A=this.o=null;this.I=(0,g.A)(this.cP,this);this.F=(0,g.A)(this.El,this);this.G=(0,g.A)(this.bP,this);this.J=(0,g.A)(this.pP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Mu,this),eza(this))):c=3;0!=c&&(b?this.Mu(c):g.VE((0,g.A)(function(){this.Mu(c)},this),0));
var d=$ya();d&&r8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},t8=function(a){return new g.JI(a.B.getPlayerContextData())},fza=function(a,b,c,d,e){var f=t8(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.NI(f,b,d);g.t(c)&&(g.LI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);u8(a,"setPlaylist",l);e||v8(a,f)},eza=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Ga(this.nR,a),this))},a)},gza=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},w8=function(a,b){50>a.C.Lc()&&g.UB(a.C,b)},x8=function(a,b,c){var d=t8(a);
g.LI(d,c);-1E3!=d.g&&(d.g=b);v8(a,d)},u8=function(a,b,c){a.B.sendMessage(b,c)},v8=function(a,b){gza(a);
a.B.setPlayerContextData(g.OI(b));eza(a)},r8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.El(null));
a.A=b;a.A&&(y8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.El(a.A.media[0]))},hza=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=t8(a);b.contentId!=d.videoId&&y8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.LI(d,a.o.getEstimatedTime());v8(a,d)}else y8("No cast media video. Ignoring state update.")},y8=function(a){g.CH("CP",a)},z8=function(a,b,c){return(0,g.A)(function(a){this.jc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.jc("Retrying "+b+" using MDx browser channel."),u8(this,b,c))},a)},iza=function(a,b,c){var d=!1;
S7()||(a=new g.DI(a,b,c),a.subscribe("yt-remote-cast2-availability-change",function(a){g.oH("yt-remote-cast-available",a);g.KG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){R7("onReceiverSelected: "+a.friendlyName);
g.oH("yt-remote-cast-receiver",a);g.KG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){R7("onReceiverResumed: "+a.friendlyName);
g.oH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){R7("onSessionChange: "+g.KH(a));
a||g.qH("yt-remote-cast-receiver");g.KG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),d=!0);
R7("cloudview.createSingleton_: "+d);return d},jza=function(){var a=0<=g.Lb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.pF||a},A8=function(a,b){Z7()?S7().setConnectedScreenStatus(a,b):a8("setConnectedScreenStatus called before ready.")},kza=function(){R7("clearCurrentReceiver");
g.qH("yt-remote-cast-receiver")},lza=function(){if(e8("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){cza();a({command:"cast.sender.init"});return}}if(!window.chrome||e8("Edge"))d8();else if(cza(),e8("Android")&&e8("Chrome/")&&window.navigator.presentation){a="";var b=g.Oh();55<=b?a="55":50<=b&&(a="50");f8("//www.gstatic.com/eureka/clank"+a+g.Ara,d8)}else k8(0)},mza=function(a){a?(g.oH("yt-remote-session-app",a.app),g.oH("yt-remote-session-name",a.name)):(g.qH("yt-remote-session-app"),g.qH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},nza=function(){var a=g8();
if(g.$b(a)){a=g.VH();var b=g.pH("yt-remote-session-name")||"",c=g.pH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},oza=function(){var a=n8();
a?(o8("Resume connection to: "+g.KH(a)),m8(a,0)):(g.cI(),kza(),o8("Skipping connecting because no session screen found."))},pza=function(a){o8("remote.onCastSessionChange_: "+g.KH(a));
if(a){var b=j8();b&&b.id==a.id?A8(b.id,"YouTube TV"):(b&&q8(),m8(a,1))}else T7()&&q8()},qza=function(){var a=dza(),b=j8();
b||(b=n8());return g.gb(a,function(a){return b&&g.HH(b,a.key)?!0:!1})},rza=function(){var a=g.pH("yt-remote-cast-receiver");
return a?a.friendlyName:null},sza=function(a,b,c,d,e,f){jza()?iza(b,e,f)&&(Y7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Zya(a,c):(window.__onGCastApiAvailable=function(b,d){b?Zya(a,c):(a8("Failed to load cast API: "+d),$7(!1),Y7(!1),g.qH("yt-remote-cast-available"),g.qH("yt-remote-cast-receiver"),Tya(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):aza():lza())):R7("Cannot initialize because not running Chrome")},
tza=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Jg(a)||"";b&&(this.port=":"+b);this.domain=g.Ig(a)||"";a=g.Lb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ya(a,"10.0")&&(this.o=!1))},B8=function(){var a=qza();
!a&&b8()&&rza()&&(a={key:"cast-selector-receiver",name:rza()});return a},uza=function(){var a=dza();
b8()&&g.pH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},vza=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.lE("MDX_CONFIG")||b;g.mH&&Nya();g.XH();l8||(l8=new tza(b?b.loungeApiHost:void 0),g.eI()&&(l8.g="/api/loungedev"));h8||(h8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",h8,void 0));nza();var c=X7();if(!c){var d=new g.pI(l8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=X7();sza(a,d,function(a){a?V7()&&A8(V7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.KG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),
b?b.appId:void 0,b?b.n3:!1)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),o8("Initializing: "+g.Ag(b)),C8.push(g.GG("yt-remote-cast2-availability-change",function(){g.KG("yt-remote-receiver-availability-change")})),C8.push(g.GG("yt-remote-cast2-receiver-selected",function(){U7(null);
g.KG("yt-remote-auto-connect","cast-selector-receiver")})),C8.push(g.GG("yt-remote-cast2-receiver-resumed",function(){g.KG("yt-remote-receiver-resumed","cast-selector-receiver")})),C8.push(g.GG("yt-remote-cast2-session-change",pza)),C8.push(g.GG("yt-remote-connection-change",function(a){a?A8(V7(),"YouTube TV"):n8()||(A8(null,null),kza())})),a=g8(),b.isAuto&&(a.id+="#dial"),g.zF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),o8(" -- with channel params: "+
g.Ag(a)),mza(a),c.start(),V7()||oza())},D8=function(){b8()?S7()?Z7()?(R7("Requesting cast selector."),S7().requestSession()):(R7("Wait for cast API to be ready to request the session."),c8.push(g.GG("yt-remote-cast2-api-ready",D8))):a8("requestCastSelector: Cast is not initialized."):a8("requestCastSelector: Cast API is not installed!")},E8=function(a,b,c){g.K.call(this);
this.F=a;this.T=b;this.o=new g.qG(this);g.L(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.oQ);this.o.P(b,"captionschanged",this.aP);this.o.P(b,"captionssettingschanged",this.VC);this.o.P(b,"videoplayerreset",this.Go);this.o.P(b,"mdxautoplaycancel",this.MH);this.N=this.o.P(b,"onVolumeChange",this.rB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.DB,this);c.subscribe("remotePlayerChange",this.Hl,this);c.subscribe("remoteQueueChange",this.Go,this);c.subscribe("autoplayUpNext",this.eB,
this);c.subscribe("previousNextChange",this.AB,this);c.subscribe("nowAutoplaying",this.sB,this);c.subscribe("autoplayDismissed",this.dB,this);this.suggestion=null;this.G=new g.gR(64);this.A=new g.Ft(this.QC,500,this);g.L(this,this.A);this.B=new g.Ft(this.RC,1E3,this);g.L(this,this.B);this.C={};this.J=new g.Ft(this.rD,1E3,this);g.L(this,this.J);this.I=new g.sk(this.WM,1E3,this);g.L(this,this.I);this.L=g.y;this.VC();this.Go();this.Hl()},F8=function(a,b){var c=a.F,d=a.T.fa().lengthSeconds;
c.I=b||0;c.g.X("progresssync",b,d)},wza=function(a){F8(a,0);
a.A.stop();G8(a,new g.gR(64))},I8=function(a,b){if(H8(a)&&!a.D){var c=null;
b&&(c={style:a.T.yi()},g.gc(c,b));a.g.JC(a.T.fa().videoId,c);a.C=t8(a.g).o}},J8=function(a,b){var c=a.T.Wf();
c?fza(a.g,a.T.fa().videoId,b,c.be(),c.listId.toString()):fza(a.g,a.T.fa().videoId,b);G8(a,new g.gR(1))},xza=function(a,b){if(b){var c=a.T.yc("captions","tracklist",{Uy:1});
c&&c.length?(a.T.Ed("captions","track",b),a.D=!1):(a.T.ql("captions"),a.D=!0)}else a.T.Ed("captions","track",{})},H8=function(a){return t8(a.g).videoId==a.T.fa().videoId},G8=function(a,b){a.B.stop();
var c=a.G;if(!g.mR(c,b)){var d=g.W(b,2);if(d!=g.W(a.G,2)){var e=a.T;g.y1(e.app,d,e.playerType)}a.G=b;yza(a.F,c,b)}},K8=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.qE()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.jX(this,250);g.L(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);zza(this,g.fW(a))},zza=function(a,b){if(3==a.A.Ya()){var c={RECEIVER_NAME:a.A.yc("remote","currentReceiver").name};
c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.wb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.Ea("statustext",c);a.o.show()}else a.o.hide()},L8=function(a){g.bX.call(this,a);
this.A={key:g.MH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.gR(64);this.I=0;var b=g.ZV(a).F;b&&(b=b.A&&b.A.g)&&(b=new P7(a,b),g.L(this,b));b=new K8(a);g.L(this,b);g.zW(a,b.element,4)},yza=function(a,b,c){a.F=c;
a.g.X("presentingplayerstatechange",new g.rR(c,b))},M8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)q8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.fa().videoId;if(c||d){var e=a.g.Wf();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.dc(k).videoId}else f=[a.g.fa().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.Iz(),0),currentTime:a.g.getCurrentTime()}}else c=null;o8("Connecting to: "+g.Ag(b));"cast-selector-receiver"==b.key?(U7(c||null),c=c||null,Z7()?S7().setLaunchParams(c):a8("setLaunchParams called before ready.")):!c&&p8()&&V7()==b.key?g.KG("yt-remote-connection-change",!0):
(q8(),U7(c||null),c=X7().ee(),(c=g.OH(c,b.key))&&m8(c,1))}};
g.p(P7,g.G0);P7.prototype.I=function(){var a=this.T.yc("remote","receivers");a&&1<a.length&&!this.T.yc("remote","quickCast")?(this.F=g.Ib(a,this.B,this),g.H0(this,(0,g.J)(a,this.B)),a=this.T.yc("remote","currentReceiver"),this.nf(this.B(a)),this.enable(!0)):this.enable(!1)};
P7.prototype.B=function(a){return a.key};
P7.prototype.mf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
P7.prototype.rd=function(a){g.G0.prototype.rd.call(this,a);this.T.Ed("remote","currentReceiver",this.F[a]);this.A.Ub()};
g.D(Q7,g.PH);g.h=Q7.prototype;g.h.ee=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.Fp=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.qp=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.dd.$_ubk(this.o[a]);this.o.length=0;this.dd=null;Q7.Z.W.call(this)};
g.h.GU=function(){this.X("screenChange")};
g.h.VQ=function(){this.X("onlineScreenChange")};
var W7=null,c8=[],h8=null,l8=null;g.D(s8,g.tG);g.h=s8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,z8(this,"play")):u8(this,"play"),x8(this,1,g.MI(t8(this))),this.X("remotePlayerChange")):w8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,z8(this,"pause")):u8(this,"pause"),x8(this,2,g.MI(t8(this))),this.X("remotePlayerChange")):w8(this,this.pause)};
g.h.DD=function(a){if(1==this.g){if(this.o){var b=t8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.wb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,z8(this,"seekTo",{newTime:a}))}else u8(this,"seekTo",{newTime:a});x8(this,3,a);this.X("remotePlayerChange")}else w8(this,g.Ga(this.DD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,z8(this,"stopVideo")):u8(this,"stopVideo");var a=t8(this);a.index=-1;a.videoId="";g.KI(a);v8(this,a);this.X("remotePlayerChange")}else w8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=t8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.A)(function(){y8("set receiver volume: "+d)},this),(0,g.A)(function(){this.jc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.A)(function(){y8("set receiver muted: "+b)},this),(0,g.A)(function(){this.jc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);u8(this,"setVolume",e)}c.muted=b;c.volume=a;v8(this,c)}else w8(this,g.Ga(this.setVolume,a,b))};
g.h.JC=function(a,b){if(1==this.g){var c=t8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ag(b.style),g.gc(d,c.o));u8(this,"setSubtitlesTrack",d);v8(this,c)}else w8(this,g.Ga(this.JC,a,b))};
g.h.Lu=function(a,b){if(1==this.g){u8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Sc.id});var c=t8(this);c.audioTrackId=b.Sc.id;v8(this,c)}else w8(this,g.Ga(this.Lu,a,b))};
g.h.CD=function(a,b){if(1==this.g){if(a&&b){var c=t8(this);g.NI(c,a,b);v8(this,c)}u8(this,"previous")}else w8(this,g.Ga(this.CD,a,b))};
g.h.BD=function(a,b){if(1==this.g){if(a&&b){var c=t8(this);g.NI(c,a,b);v8(this,c)}u8(this,"next")}else w8(this,g.Ga(this.BD,a,b))};
g.h.mx=function(){1==this.g?u8(this,"dismissAutoplay"):w8(this,this.mx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.X("proxyStateChange",a,this.g)}s8.Z.dispose.call(this)};
g.h.W=function(){gza(this);this.B=null;this.C.clear();r8(this,null);s8.Z.W.call(this)};
g.h.Mu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.X("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.VB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.nR=function(a,b){this.X(a,b)};
g.h.cP=function(a){if(!a)this.El(null),r8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=t8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)y8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,v8(this,b)}};
g.h.El=function(a){y8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),hza(this),this.X("remotePlayerChange")};
g.h.bP=function(a){a?(hza(this),this.X("remotePlayerChange")):this.El(null)};
g.h.pP=function(){var a=$ya();a&&r8(this,a)};
g.h.jc=function(a){g.CH("CP",a)};
var C8=[];g.h=tza.prototype;g.h.ji=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Qg(b+a,{})};
g.h.Ku=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Vb:g.Ga(this.BU,c,!0),onError:g.Ga(this.AU,d),Gd:g.Ga(this.CU,d)};b&&(c.Nb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.iF(a,c)};
g.h.BU=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.AU=function(a,b){a(Error("Request error: "+b.status))};
g.h.CU=function(a){a(Error("request timed out"))};g.p(E8,g.K);g.h=E8.prototype;g.h.W=function(){g.K.prototype.W.call(this);this.A.stop();this.B.stop();this.L();this.g.unsubscribe("proxyStateChange",this.DB,this);this.g.unsubscribe("remotePlayerChange",this.Hl,this);this.g.unsubscribe("remoteQueueChange",this.Go,this);this.g.unsubscribe("autoplayUpNext",this.eB,this);this.g.unsubscribe("previousNextChange",this.AB,this);this.g.unsubscribe("nowAutoplaying",this.sB,this);this.g.unsubscribe("autoplayDismissed",this.dB,this);this.g=this.F=null};
g.h.iA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(H8(this)){if(1081!=t8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":t8(this.g).wb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.mj(c[0],c[1]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":c=c[0],H8(this)&&this.g.Lu(this.T.fa().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":J8(this,this.T.getCurrentTime());break;case "control_seek":J8(this,c[0]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":c=c[0],H8(this)&&this.g.Lu(this.T.fa().videoId,c)}};
g.h.aP=function(a){this.iA("control_subtitles_set_track",g.$b(a)?null:a)};
g.h.VC=function(){var a=this.T.yc("captions","track");g.$b(a)||I8(this,a)};
g.h.rB=function(a){if(H8(this)){this.g.unsubscribe("remotePlayerChange",this.Hl,this);var b=Math.round(a.volume);a=!!a.muted;var c=t8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.J.start();this.g.subscribe("remotePlayerChange",this.Hl,this)}};
g.h.oQ=function(){g.$b(this.C)||xza(this,this.C);this.D=!1};
g.h.DB=function(a,b){this.B.stop();2==b&&this.RC()};
g.h.Hl=function(){if(H8(this)){this.A.stop();var a=t8(this.g);switch(a.g){case 1081:G8(this,new g.gR(8));break;case 1:this.QC();G8(this,new g.gR(8));break;case 1083:case 3:G8(this,new g.gR(9));break;case 0:G8(this,new g.gR(2));this.I.stop();F8(this,this.T.fa().lengthSeconds);break;case 1082:G8(this,new g.gR(4));break;case 2:G8(this,new g.gR(4));F8(this,g.MI(a));break;case -1:G8(this,new g.gR(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},G8(this,new g.gR(128,
a))}a=t8(this.g).o;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,xza(this,a));a=t8(this.g);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.Ke()==a.muted||this.J.isActive()||this.rD()}else wza(this)};
g.h.AB=function(){this.T.X("mdxpreviousnextchange")};
g.h.Go=function(){H8(this)||wza(this)};
g.h.MH=function(){this.g.mx()};
g.h.eB=function(a){a&&(a=g.iF("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Vb:(0,g.A)(this.oS,this)}))&&(this.L=(0,g.A)(a.abort,a))};
g.h.oS=function(a,b){var c=new g.eQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.X("mdxautoplayupnext",c)};
g.h.sB=function(a){(0,window.isNaN)(a)||this.T.X("mdxnowautoplaying",a)};
g.h.dB=function(){this.T.X("mdxautoplaycanceled")};
g.h.WM=function(a,b){-1==t8(this.g).g?J8(this,a):b&&this.g.DD(a)};
g.h.rD=function(){if(H8(this)){var a=t8(this.g);this.o.Ca(this.N);a.muted?this.T.mute():this.T.Zf();this.T.setVolume(a.volume);this.N=this.o.P(this.T,"onVolumeChange",this.rB)}};
g.h.QC=function(){this.A.stop();if(!this.g.la()){var a=t8(this.g);a.wb()&&G8(this,new g.gR(8));F8(this,g.MI(a));this.A.start()}};
g.h.RC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(K8,g.Y);K8.prototype.B=function(a){zza(this,a.state)};g.p(L8,g.bX);g.h=L8.prototype;g.h.create=function(){vza(g.eO(g.X(this.g)));this.D.push(g.GG("yt-remote-before-disconnect",this.XO,this));this.D.push(g.GG("yt-remote-connection-change",this.xR,this));this.D.push(g.GG("yt-remote-receiver-availability-change",this.BB,this));this.D.push(g.GG("yt-remote-auto-connect",this.vR,this));this.D.push(g.GG("yt-remote-receiver-resumed",this.uR,this));this.BB()};
g.h.load=function(){this.g.wq();g.bX.prototype.load.call(this);this.C=new E8(this,this.g,this.o);var a=Yya();a=a?a.currentTime:0;var b=p8()?new s8(T7(),void 0):null;0==a&&b&&(a=g.MI(t8(b)));0!=a&&(this.I=a||0,this.g.X("progresssync",a,void 0));yza(this,this.F,this.F);g.D1(this.g.app,6)};
g.h.unload=function(){this.g.X("mdxautoplaycanceled");this.B=this.A;g.bf(this.C,this.o);this.o=this.C=null;g.bX.prototype.unload.call(this);g.D1(this.g.app,5)};
g.h.W=function(){g.HG(this.D);g.bX.prototype.W.call(this)};
g.h.wl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.iA.apply(this.C,[].concat([a],g.pa(c)))};
g.h.xI=function(){return this.loaded?this.C.suggestion:null};
g.h.Pf=function(){return this.o?t8(this.o).Pf:!1};
g.h.hasNext=function(){return this.o?t8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.zM=function(){var a=t8(this.o),b=this.g.fa();return{allowSeeking:this.g.Pd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.G)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.G)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.F?a.B+((0,g.G)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.G)()-a.A)/1E3:a.D}};
g.h.AM=function(){this.o&&this.o.BD()};
g.h.BM=function(){this.o&&this.o.CD()};
g.h.XO=function(a){1==a&&(this.J=this.o?t8(this.o):null)};
g.h.xR=function(){var a=p8()?new s8(T7(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.af(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.fa().videoId&&this.g.Gz(a.videoId,g.MI(a)));this.g.X("videodatachange","newdata",this.g.fa(),3)};
g.h.BB=function(){this.G=[this.A].concat(uza());var a=B8()||this.A;M8(this,a);this.g.za("onMdxReceiversChange")};
g.h.vR=function(){var a=B8();M8(this,a)};
g.h.uR=function(){this.B=B8()};
g.h.yM=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?D8():M8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&D8(),!0):!1}};
g.h.CM=function(){u8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.sd=function(){return!1};g.nX("remote",L8);})(_yt_player);
